channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - pip:
      - lightgbm==3.3.1
      - matplotlib==3.3.4
      - scikit-learn==0.24.2
      - pandas==1.1.5
      - ipykernel
      - azureml-mlflow
      - azureml-dataprep
      - azureml-defaults
  - pip
name: lightgbm-python-env